name: Merge release to develop

on:
   push:
      branches:
         - 'release/**'
env:
    GH_TOKEN: ${{ github.token }}

jobs:
   merge:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Merge release to develop
           run: |
              branch="${{ github.ref_name }}"
              gh pr create --base develop --head $branch --title "Merge: develop <- $branch" --body "## Merge 내용
              \`develop\` 브랜치에 \`$branch\` 브랜치를 병합합니다.
              ### Create a merge commit"
